### ISSUE TITLE
Contest Admin

### ISSUE THREAD

**Issue by karenbanzon** [karenbanzon/teedlee#10]
Create the area similar to how we manage submissions, but for contests.

Backend Nuances:
- For new submissions, if they have not been approved / rejected, push to public voting after 24hrs
- Internal and public voting for contests happen simultaneously (no need to pass internal voting before being pushed to public voting

Frontend States (@karenbanzon to create templates):
- [ ] Submissions open
- [ ] Submissions closed, voting ongoing
- [ ] Voting complete, awaiting results, display entries
- [ ] Contest closed, display winners

**Comment by jhourlad** [comment]
Done. For testing.
