### ISSUE TITLE
Vote Landing Page

### ISSUE THREAD

**Issue by ryanjaycrisostomo** [karenbanzon/teedlee#12]
Add a LINE in between ENTRIES FROM OPEN SUBMISSION and CONTEST #1 to create separation.

![screen shot 2016-11-30 at 12 39 21 pm](https://cloud.githubusercontent.com/assets/22937470/20740100/678a3e6c-b6fb-11e6-88aa-18e4c97b6e39.png)

**Comment by jhourlad** [comment]
Fixed.
