### ISSUE TITLE
Design Submission

### ISSUE THREAD

**Issue by ryanjaycrisostomo** [karenbanzon/teedlee#14]
- [ ] Fix "300 characters left" in Description — should change as description is typed
![screen shot 2016-11-30 at 1 01 47 pm](https://cloud.githubusercontent.com/assets/22937470/20740520/abf8f04a-b6fe-11e6-803f-d4c476f30fcd.png)

- [ ] Change ladning page after submission to https://dev.teedlee.ph/user/entries if submitting via contest (currently landing on https://dev.teedlee.ph/user/submissions when submitting via contest)

**Comment by jhourlad** [comment]
1. Added textbox indicator and limiter script.
2. Issue addressed in Issue #17 

For testing.
