### ISSUE TITLE
Contest Submission

### ISSUE THREAD

**Issue by ryanjaycrisostomo** [karenbanzon/teedlee#15]
SUBMIT button not appearing after submission dates have been changed

![screen shot 2016-11-30 at 1 31 31 pm](https://cloud.githubusercontent.com/assets/22937470/20740995/5866f8ba-b702-11e6-8e83-122f832d706f.png)
![screen shot 2016-11-30 at 1 33 34 pm](https://cloud.githubusercontent.com/assets/22937470/20740994/5866a4c8-b702-11e6-8ac2-e26f83d753ac.png)

**Comment by jhourlad** [comment]
Fixed.
