### ISSUE TITLE
Change contest banner

### ISSUE THREAD

**Issue by ryanjaycrisostomo** [karenbanzon/teedlee#16]
Check if "UPLOAD IMAGE" is working. Banner can't be changed right now. Showing broken image when uploading .PNG. Showing old image when uploading .JPG.

![screen shot 2016-11-30 at 3 03 36 pm](https://cloud.githubusercontent.com/assets/22937470/20742955/88c4afaa-b70e-11e6-954d-df96e1cb63f6.png)

**Comment by jhourlad** [comment]
Fixed. For checking.
