### ISSUE TITLE
New submissions get status "For Voting", should be "Pending" until 24 hours.

### ISSUE THREAD

**Issue by karenbanzon** [karenbanzon/teedlee#18]
![image](https://cloud.githubusercontent.com/assets/4230234/20744071/b718d10a-b714-11e6-85a3-191a66f5321d.png)

Behaviour should be:
- entries can be voted on 24 hours after submission if not rejected
- instead of "For Voting", please indicate "Pending" until the 24 hour period ends

**Comment by jhourlad** [comment]
1. This was already in the code since last Monday. Kindly recheck if indeed not working.
2. Added "Pending" status.

**Comment by karenbanzon** [comment]
@jhourlad still not fixed.

Please double check behavior.

1. Entries can be voted on 24 hours after submission if not rejected. During this period they should have a status of "Pending". When they have passed the 24 hour period, they will have the status "For Voting"

2. Entries should only show up in the vote area after the 24 hour period. All entries are showing up now.

**Comment by jhourlad** [comment]
1 and 2 fixed.
