### ISSUE TITLE
Add sign up modal to vote pages

### ISSUE THREAD

**Issue by ryanjaycrisostomo** [karenbanzon/teedlee#21]
Page template: `public/static/template-voting-with-modal.php`

![image](https://cloud.githubusercontent.com/assets/4230234/20827384/969bb426-b8ac-11e6-9918-1ac40753520f.png)

Notes:
1. Upon landing on voting page from FB or from vote landing page, user sees a modal.
2. Buttons are "Sign up to vote" and "View Next"
3. When clicking "Sign up to vote", modal appears again.

Nuance:
- Coming from email verification, user should be able to see the original submission they were viewing so they can cast their vote.

**Comment by karenbanzon** [comment]
@jhourlad updated the description!

**Comment by jhourlad** [comment]
Done. For QA testing.
