### ISSUE TITLE
Regular accounts not able to view live contest entries to vote

### ISSUE THREAD

**Issue by karenbanzon** [karenbanzon/teedlee#22]
See screenshots:

![screen shot 2016-12-01 at 5 39 05 pm](https://cloud.githubusercontent.com/assets/4230234/20789887/0ee69340-b7f1-11e6-8555-c9508253d158.png)

![screen shot 2016-12-01 at 5 40 35 pm](https://cloud.githubusercontent.com/assets/4230234/20789891/12396ffe-b7f1-11e6-9ac0-929e18fec959.png)

**Comment by jhourlad** [comment]
This might be a CRON job problem. Checking if running.

**Comment by jhourlad** [comment]
Fixed.
