### ISSUE TITLE
Contest edits

### ISSUE THREAD

**Issue by karenbanzon** [karenbanzon/teedlee#24]
- [x] Remove description in contest listings
- [x] Add "Learn more" link beside Vote/Submit button in contest listings
- [x] Fix content landing page scraping meta (image, title, description)
- [x] Add vote button (below featured image) in contest landing page if voting is ongoing
- [x] Add submit button in contest landing page (below featured image) if submissions are open

----------

Note from @karenbanzon: Please double check the ff.

- [x] "Learn more" link should be visible on all types of contest listing pages (vote landing, submit landing, voting done)

Submit landing (https://dev.teedlee.ph/submit)
![image](https://cloud.githubusercontent.com/assets/4230234/21305085/63c36afc-c604-11e6-8a30-e7a5c70d94aa.png)

Vote landing (https://dev.teedlee.ph/vote)
![image](https://cloud.githubusercontent.com/assets/4230234/21305111/8d2948bc-c604-11e6-87e5-c2ad021372ac.png)

Vote done, show other contests & open submission (https://dev.teedlee.ph/vote/done?contest=1)
![image](https://cloud.githubusercontent.com/assets/4230234/21305192/1caf5eea-c605-11e6-97e4-4686644eb334.png)

----------

- [x] Vote button in contest landing page should only show up if voting is ongoing, as stated above
- [x] Submit button in contest landing page should only show up if submissions are open, as stated above

Sample url used in screens below: https://dev.teedlee.ph/contest/1

Vote & Submit buttons showing even when submission and voting closed:
![image](https://cloud.githubusercontent.com/assets/4230234/21305150/cbd93cac-c604-11e6-8408-ae36ef290486.png)

Able to submit even if contest is closed:
![image](https://cloud.githubusercontent.com/assets/4230234/21305185/0e4fce66-c605-11e6-9251-0392cc2323ba.png)

----------

- [x] Scraping info is not correct, only title is fetched properly (image: contest image, description, contest description)

Facebook debugger, scraped fresh data
![image](https://cloud.githubusercontent.com/assets/4230234/21305234/663e2b22-c605-11e6-8b41-29dff7aac62e.png)

**Comment by jhourlad** [comment]
Done. For QA.

**Comment by jhourlad** [comment]
Fixed reported issues. For checking.
