### ISSUE TITLE
Voting open, but when I go in, sabi no more entries.

### ISSUE THREAD

**Issue by jhourlad** [karenbanzon/teedlee#25]
![image](https://cloud.githubusercontent.com/assets/3771945/21412417/1566740c-c82b-11e6-89fb-816b92a1b4c2.png)

Saka sabi Contest#1, but this is Test Contest A.
Di maka go through yung simulation.. Please update.

![Uploading image.png…]()

**Comment by jhourlad** [comment]
For QA.

**Comment by karenbanzon** [comment]
Fixed. Closing.
