### ISSUE TITLE
Test handshake with Shopify API

### ISSUE THREAD

**Issue by ryanjaycrisostomo** [karenbanzon/teedlee#3]
Get all the data we can pull from Shopify.

Check if we can pull the ff. data:
- total sales per vendor
- total earnings per item (shop item name, total sales)
- sales history per design ID (invoice number, quantity, date of sale, item sold to)
- pull from "0003_test_handshake_with_shopify_api" branch

**Comment by jhourlad** [comment]
- @karenbanzon Need layout for user/sales and sales/{id}
- pull from "0003_test_handshake_with_shopify_api" branch

**Comment by jhourlad** [comment]
Closing this in favor of https://github.com/karenbanzon/teedlee/issues/4
