### ISSUE TITLE
Integrate data with user profile

### ISSUE THREAD

**Issue by ryanjaycrisostomo** [karenbanzon/teedlee#4]
Vendor name in Shopify = Teedlee username
- [x] Remove ability to edit username
- [x] Display data in User Profile - Sales
- [x] @karenbanzon: Update page template (see below)
- [x] @jhourlad: see page template 

![sales-monitoring-01](https://cloud.githubusercontent.com/assets/22937470/19719086/f3eee348-9b9a-11e6-8bd9-c1c04353bac5.png)
![sales-monitoring-02](https://cloud.githubusercontent.com/assets/22937470/19719087/f49c8d54-9b9a-11e6-92cf-2de717651181.png)

**Comment by karenbanzon** [comment]
@jhourlad templates added:

`public/static/template-sales-breakdown.php`
`public/static/template-sales-overview.php`

Assigining now to you.

**Comment by jhourlad** [comment]
Anong branch ma'am nakalagay yung templates?
