### ISSUE TITLE
Fix Facebook scraping of shared entries for public voting

### ISSUE THREAD

**Issue by ryanjaycrisostomo** [karenbanzon/teedlee#5]
Problem: Link shared on Facebook has no proper image and title. Need to fix meta tags scraped by Facebook.

Meta tags to be set:

`<meta property="og:title" content="Vote for [design title] by [artist]" />`
`<meta property="og:description"  content="Teedlee is a clothing brand powered by artists. We produce and sell crowd-sourced graphic designs from our community, where the artist of this design will earn a profit from your purchases." />`
`<meta property="og:image" content="[design image url]" />`

![screen shot 2016-10-26 at 4 14 30 pm](https://cloud.githubusercontent.com/assets/22937470/19718291/55708a9e-9b97-11e6-90ee-069fd7141c03.png)
- [x] Title format: "Vote for [design title] by [artist]"
- [x] Description: "Teedlee is a clothing brand powered by artists. We produce and sell crowd-sourced graphic designs from our community, where the artist of this design will earn a profit from your purchases."
- [x] Image: Design image

**Comment by jhourlad** [comment]
Fixed submission data error on open graph

**Comment by karenbanzon** [comment]
This is fixed. Closing issue.
