### ISSUE TITLE
Improve deployment process

### ISSUE THREAD

**Issue by karenbanzon** [karenbanzon/teedlee#6]
Ideal behavior:
- deployment script can be passed a variable (github branch name) to pull from
- if no variable specified, deploy from master

**Comment by karenbanzon** [comment]
@jhourlad please comment below what our deploy command for a branch is, para we can close the ticket already. Thanks.

**Comment by jhourlad** [comment]
Done. Usage:
Deploy [branch|"master"]

**Comment by jhourlad** [comment]
Done. Usage:
Deploy [branch|"master"]
