### ISSUE TITLE
Install Facebook Pixel to the main site and shopify site

### ISSUE THREAD

**Issue by ryanjaycrisostomo** [karenbanzon/teedlee#7]
Pixel ID: 784713281655514

**Comment by ryanjaycrisostomo** [comment]
How do I put this to the pending column?

**Comment by karenbanzon** [comment]
@ryanjaycrisostomo FB pixel is already in Shopify

**Comment by karenbanzon** [comment]
Done, branch `0007-facebook-pixel` merged to master
