### ISSUE TITLE
"Create Contest" in Admin

### ISSUE THREAD

**Issue by karenbanzon** [karenbanzon/teedlee#9]
Recommended fields

- Title
- Contest ID
- Duration (Date & Time) (Start and End)
- Featured Image
- Description (Rich Text)
- Contest Judges

Just message if you have any questions / clarifications, @jhourlad.

Templates for where the Featured Image will appear in the frontend are here:
`/static/template-vote-landing.php`
- Vote Landing page with contests area below open submission area

`/static/template-vote-empty-contest.php`
- Page when a user has finished voting for all entries in a contest, and is led to vote for open submissions

`/static/template-vote-empty-open-submission.php`
- Page when a user has finished voting for all entries in a contest, and is led to vote for contests

**Comment by jhourlad** [comment]
@karenbanzon Can we make the fields _start_ and _end_ instead of _duration_?

**Comment by karenbanzon** [comment]
@jhourlad, I added the ff. templates:

`/static/template-contest-single-landing-contest-closed-show-winners.php`
`/static/template-contest-single-landing-submission-open.php`
`/static/template-contest-single-landing-submission-voting-closed.php`
`/static/template-contest-single-landing-voting-ongoing.php`
